hw09 implementation
tw1337/2024-03-otus-spring-Mysyanov pull request #9
Opened 2024-06-21 17:55 UTC by tw1337

2024-06-26 17:35 UTC, VladimirMagerov requested changes

2024-06-26 17:35 UTC, VladimirMagerov commented on hw09/src/test/java/ru/otus/hw/controller/BookControllerTest.java
> +public class BookControllerTest {
В контроллерах тестами покрыты только позитивные сценарии, предлагаю покрыть и негативные (те, в процессе которых возникает исключение, например).

2024-06-26 17:35 UTC, VladimirMagerov commented on hw09/src/main/resources/templates/book/all.html
> +        <form id="delete-book" action="all.html" th:method="post" th:action="@{/book/delete/{id}(id = ${book.id})}">
Опционально - было бы круто сделать так, чтобы перед удалением у пользователя запрашивалось подтверждение, уверен ли он что он хочет удалить запись.

2024-06-27 16:14 UTC, tw1337 commented on hw09/src/test/java/ru/otus/hw/controller/BookControllerTest.java
> +public class BookControllerTest {
fixed

2024-06-27 16:14 UTC, tw1337 commented on hw09/src/main/resources/templates/book/all.html
> +        <form id="delete-book" action="all.html" th:method="post" th:action="@{/book/delete/{id}(id = ${book.id})}">
won't fix

2024-06-29 17:32 UTC, VladimirMagerov approved these changes

2024-06-30 06:23 UTC, merged